server:
  port: 0

spring:
  cloud:
    config:
      name: user-service
  config:
    import: optional:configserver:http://localhost:8888

  application:
    name: user-service

  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

#  datasource:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/cloud
#      username: sa
#      password:

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Hi

logging:
  level:
    com.example.userservice.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus

#token:
#  expiration_time: 86400000
#  secret: user_token